//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndignaFwk.UI.Process.ConvocatoriaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost//IndignaFwk//2012", ConfigurationName="ConvocatoriaService.IConvocatoriaService")]
    public interface IConvocatoriaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost//IndignaFwk//2012/IConvocatoriaService/crearConvocatoria", ReplyAction="http://localhost//IndignaFwk//2012/IConvocatoriaService/crearConvocatoriaResponse" +
            "")]
        int crearConvocatoria(IndignaFwk.Business.Entities.Convocatoria convocatoria);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConvocatoriaServiceChannel : IndignaFwk.UI.Process.ConvocatoriaService.IConvocatoriaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConvocatoriaServiceClient : System.ServiceModel.ClientBase<IndignaFwk.UI.Process.ConvocatoriaService.IConvocatoriaService>, IndignaFwk.UI.Process.ConvocatoriaService.IConvocatoriaService {
        
        public ConvocatoriaServiceClient() {
        }
        
        public ConvocatoriaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConvocatoriaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvocatoriaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvocatoriaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int crearConvocatoria(IndignaFwk.Business.Entities.Convocatoria convocatoria) {
            return base.Channel.crearConvocatoria(convocatoria);
        }
    }
}
