//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndignaFwk.Business.Agents.WikipediaService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WikipediaService.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCandidatesFromKeyword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCandidatesFromKeyword(string Keyword, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTopCandidateIDFromKeyword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        uint GetTopCandidateIDFromKeyword(string Keyword, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCandidateFromID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCandidateFromID(uint ID, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSynonym", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSynonym(uint iID, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetThesaurusDS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetThesaurusDS(int iType, uint iFrom, int iOffset, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetThesaurusDS300", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetThesaurusDS300(int iType, uint iFrom, int iOffset, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetThesaurusDS4NetworkView", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetThesaurusDS4NetworkView(uint iFrom, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetThesaurus4NetworkView", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetThesaurus4NetworkView(uint iFrom, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetThesaurusDSFromTitles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetThesaurusDSFromTitles(int iType, string[] sTitles, int iOffset, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIDFromTitle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        uint GetIDFromTitle(string sTitle, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIDFromTitleWithConnect", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        uint GetIDFromTitleWithConnect(string sTitle, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTagCandidates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetTagCandidates(string PatternHead, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTagCandidatesExperiment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetTagCandidatesExperiment(string PatternHead, int DisplayType, int SearchType, string language);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : IndignaFwk.Business.Agents.WikipediaService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<IndignaFwk.Business.Agents.WikipediaService.ServiceSoap>, IndignaFwk.Business.Agents.WikipediaService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetCandidatesFromKeyword(string Keyword, string language) {
            return base.Channel.GetCandidatesFromKeyword(Keyword, language);
        }
        
        public uint GetTopCandidateIDFromKeyword(string Keyword, string language) {
            return base.Channel.GetTopCandidateIDFromKeyword(Keyword, language);
        }
        
        public System.Data.DataSet GetCandidateFromID(uint ID, string language) {
            return base.Channel.GetCandidateFromID(ID, language);
        }
        
        public System.Data.DataSet GetSynonym(uint iID, string language) {
            return base.Channel.GetSynonym(iID, language);
        }
        
        public System.Data.DataSet GetThesaurusDS(int iType, uint iFrom, int iOffset, string language) {
            return base.Channel.GetThesaurusDS(iType, iFrom, iOffset, language);
        }
        
        public System.Data.DataSet GetThesaurusDS300(int iType, uint iFrom, int iOffset, string language) {
            return base.Channel.GetThesaurusDS300(iType, iFrom, iOffset, language);
        }
        
        public System.Data.DataSet GetThesaurusDS4NetworkView(uint iFrom, string language) {
            return base.Channel.GetThesaurusDS4NetworkView(iFrom, language);
        }
        
        public string[] GetThesaurus4NetworkView(uint iFrom, string language) {
            return base.Channel.GetThesaurus4NetworkView(iFrom, language);
        }
        
        public System.Data.DataSet GetThesaurusDSFromTitles(int iType, string[] sTitles, int iOffset, string language) {
            return base.Channel.GetThesaurusDSFromTitles(iType, sTitles, iOffset, language);
        }
        
        public uint GetIDFromTitle(string sTitle, string language) {
            return base.Channel.GetIDFromTitle(sTitle, language);
        }
        
        public uint GetIDFromTitleWithConnect(string sTitle, string language) {
            return base.Channel.GetIDFromTitleWithConnect(sTitle, language);
        }
        
        public System.Data.DataSet GetTagCandidates(string PatternHead, string language) {
            return base.Channel.GetTagCandidates(PatternHead, language);
        }
        
        public System.Data.DataSet GetTagCandidatesExperiment(string PatternHead, int DisplayType, int SearchType, string language) {
            return base.Channel.GetTagCandidatesExperiment(PatternHead, DisplayType, SearchType, language);
        }
    }
}
