//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndignaFwk.UI.Process.ContenidoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ContenidoService.IContenidoService")]
    public interface IContenidoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContenidoService/CrearNuevoContenido", ReplyAction="http://tempuri.org/IContenidoService/CrearNuevoContenidoResponse")]
        int CrearNuevoContenido(IndignaFwk.Common.Entities.Contenido contenido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContenidoService/ObtenerListadoContenidosPorGrupoYVisibilidad" +
            "", ReplyAction="http://tempuri.org/IContenidoService/ObtenerListadoContenidosPorGrupoYVisibilidad" +
            "Response")]
        System.Collections.Generic.List<IndignaFwk.Common.Entities.Contenido> ObtenerListadoContenidosPorGrupoYVisibilidad(int idGrupo, string visibilidadContenido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContenidoService/ObtenerXContenidosMasRankeadosPorGrupoYVisib" +
            "ilidad", ReplyAction="http://tempuri.org/IContenidoService/ObtenerXContenidosMasRankeadosPorGrupoYVisib" +
            "ilidadResponse")]
        System.Collections.Generic.List<IndignaFwk.Common.Entities.Contenido> ObtenerXContenidosMasRankeadosPorGrupoYVisibilidad(int idGrupo, string visibilidadContenido, int x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContenidoService/ObtenerContenidoPorId", ReplyAction="http://tempuri.org/IContenidoService/ObtenerContenidoPorIdResponse")]
        IndignaFwk.Common.Entities.Contenido ObtenerContenidoPorId(int idContenido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContenidoService/EliminarListaContenido", ReplyAction="http://tempuri.org/IContenidoService/EliminarListaContenidoResponse")]
        void EliminarListaContenido(int idContenido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContenidoService/ObtenerListadoPorGrupoNoEliminado", ReplyAction="http://tempuri.org/IContenidoService/ObtenerListadoPorGrupoNoEliminadoResponse")]
        System.Collections.Generic.List<IndignaFwk.Common.Entities.Contenido> ObtenerListadoPorGrupoNoEliminado(int idGrupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContenidoService/ObtenerContenidoEliminadoPorUsuario", ReplyAction="http://tempuri.org/IContenidoService/ObtenerContenidoEliminadoPorUsuarioResponse")]
        System.Collections.Generic.List<IndignaFwk.Common.Entities.Contenido> ObtenerContenidoEliminadoPorUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContenidoService/ObtenerMarcaContenidoPorUsuarioYContenido", ReplyAction="http://tempuri.org/IContenidoService/ObtenerMarcaContenidoPorUsuarioYContenidoRes" +
            "ponse")]
        IndignaFwk.Common.Entities.MarcaContenido ObtenerMarcaContenidoPorUsuarioYContenido(int idUsuario, int idContenido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContenidoService/CrearNuevaMarcaContenido", ReplyAction="http://tempuri.org/IContenidoService/CrearNuevaMarcaContenidoResponse")]
        int CrearNuevaMarcaContenido(IndignaFwk.Common.Entities.MarcaContenido marcaContenido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContenidoService/EditarMarcaContenido", ReplyAction="http://tempuri.org/IContenidoService/EditarMarcaContenidoResponse")]
        void EditarMarcaContenido(IndignaFwk.Common.Entities.MarcaContenido marcaContenido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContenidoService/ObtenerContenidoConMarcas", ReplyAction="http://tempuri.org/IContenidoService/ObtenerContenidoConMarcasResponse")]
        IndignaFwk.Common.Entities.Contenido ObtenerContenidoConMarcas(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContenidoService/ObtenerListadoPorGrupo", ReplyAction="http://tempuri.org/IContenidoService/ObtenerListadoPorGrupoResponse")]
        System.Collections.Generic.List<IndignaFwk.Common.Entities.Contenido> ObtenerListadoPorGrupo(int idGrupo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContenidoServiceChannel : IndignaFwk.UI.Process.ContenidoService.IContenidoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContenidoServiceClient : System.ServiceModel.ClientBase<IndignaFwk.UI.Process.ContenidoService.IContenidoService>, IndignaFwk.UI.Process.ContenidoService.IContenidoService {
        
        public ContenidoServiceClient() {
        }
        
        public ContenidoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContenidoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContenidoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContenidoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CrearNuevoContenido(IndignaFwk.Common.Entities.Contenido contenido) {
            return base.Channel.CrearNuevoContenido(contenido);
        }
        
        public System.Collections.Generic.List<IndignaFwk.Common.Entities.Contenido> ObtenerListadoContenidosPorGrupoYVisibilidad(int idGrupo, string visibilidadContenido) {
            return base.Channel.ObtenerListadoContenidosPorGrupoYVisibilidad(idGrupo, visibilidadContenido);
        }
        
        public System.Collections.Generic.List<IndignaFwk.Common.Entities.Contenido> ObtenerXContenidosMasRankeadosPorGrupoYVisibilidad(int idGrupo, string visibilidadContenido, int x) {
            return base.Channel.ObtenerXContenidosMasRankeadosPorGrupoYVisibilidad(idGrupo, visibilidadContenido, x);
        }
        
        public IndignaFwk.Common.Entities.Contenido ObtenerContenidoPorId(int idContenido) {
            return base.Channel.ObtenerContenidoPorId(idContenido);
        }
        
        public void EliminarListaContenido(int idContenido) {
            base.Channel.EliminarListaContenido(idContenido);
        }
        
        public System.Collections.Generic.List<IndignaFwk.Common.Entities.Contenido> ObtenerListadoPorGrupoNoEliminado(int idGrupo) {
            return base.Channel.ObtenerListadoPorGrupoNoEliminado(idGrupo);
        }
        
        public System.Collections.Generic.List<IndignaFwk.Common.Entities.Contenido> ObtenerContenidoEliminadoPorUsuario(int idUsuario) {
            return base.Channel.ObtenerContenidoEliminadoPorUsuario(idUsuario);
        }
        
        public IndignaFwk.Common.Entities.MarcaContenido ObtenerMarcaContenidoPorUsuarioYContenido(int idUsuario, int idContenido) {
            return base.Channel.ObtenerMarcaContenidoPorUsuarioYContenido(idUsuario, idContenido);
        }
        
        public int CrearNuevaMarcaContenido(IndignaFwk.Common.Entities.MarcaContenido marcaContenido) {
            return base.Channel.CrearNuevaMarcaContenido(marcaContenido);
        }
        
        public void EditarMarcaContenido(IndignaFwk.Common.Entities.MarcaContenido marcaContenido) {
            base.Channel.EditarMarcaContenido(marcaContenido);
        }
        
        public IndignaFwk.Common.Entities.Contenido ObtenerContenidoConMarcas(int id) {
            return base.Channel.ObtenerContenidoConMarcas(id);
        }
        
        public System.Collections.Generic.List<IndignaFwk.Common.Entities.Contenido> ObtenerListadoPorGrupo(int idGrupo) {
            return base.Channel.ObtenerListadoPorGrupo(idGrupo);
        }
    }
}
