//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndignaFwk.UI.Process.GrupoReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost//IndignaFwk//2012", ConfigurationName="GrupoReference.IGrupoService")]
    public interface IGrupoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost//IndignaFwk//2012/IGrupoService/CrearGrupo", ReplyAction="http://localhost//IndignaFwk//2012/IGrupoService/CrearGrupoResponse")]
        int CrearGrupo(IndignaFwk.Common.Entities.Grupo grupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost//IndignaFwk//2012/IGrupoService/ObtenerListadoGrupos", ReplyAction="http://localhost//IndignaFwk//2012/IGrupoService/ObtenerListadoGruposResponse")]
        IndignaFwk.Common.Entities.Grupo[] ObtenerListadoGrupos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost//IndignaFwk//2012/IGrupoService/ObtenerGrupoPorUrl", ReplyAction="http://localhost//IndignaFwk//2012/IGrupoService/ObtenerGrupoPorUrlResponse")]
        IndignaFwk.Common.Entities.Grupo ObtenerGrupoPorUrl(string url);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGrupoServiceChannel : IndignaFwk.UI.Process.GrupoReference.IGrupoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GrupoServiceClient : System.ServiceModel.ClientBase<IndignaFwk.UI.Process.GrupoReference.IGrupoService>, IndignaFwk.UI.Process.GrupoReference.IGrupoService {
        
        public GrupoServiceClient() {
        }
        
        public GrupoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GrupoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GrupoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GrupoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CrearGrupo(IndignaFwk.Common.Entities.Grupo grupo) {
            return base.Channel.CrearGrupo(grupo);
        }
        
        public IndignaFwk.Common.Entities.Grupo[] ObtenerListadoGrupos() {
            return base.Channel.ObtenerListadoGrupos();
        }
        
        public IndignaFwk.Common.Entities.Grupo ObtenerGrupoPorUrl(string url) {
            return base.Channel.ObtenerGrupoPorUrl(url);
        }
    }
}
