//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndignaFwk.UI.Process.GrupoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost//IndignaFwk//2012", ConfigurationName="GrupoService.IGrupoService")]
    public interface IGrupoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost//IndignaFwk//2012/IGrupoService/crearGrupo", ReplyAction="http://localhost//IndignaFwk//2012/IGrupoService/crearGrupoResponse")]
        int crearGrupo(IndignaFwk.Business.Entities.Grupo grupo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGrupoServiceChannel : IndignaFwk.UI.Process.GrupoService.IGrupoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GrupoServiceClient : System.ServiceModel.ClientBase<IndignaFwk.UI.Process.GrupoService.IGrupoService>, IndignaFwk.UI.Process.GrupoService.IGrupoService {
        
        public GrupoServiceClient() {
        }
        
        public GrupoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GrupoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GrupoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GrupoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int crearGrupo(IndignaFwk.Business.Entities.Grupo grupo) {
            return base.Channel.crearGrupo(grupo);
        }
    }
}
