//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndignaFwk.UI.Process.AdministradorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdministradorService.IAdministradorService")]
    public interface IAdministradorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorService/CrearNuevoAdministrador", ReplyAction="http://tempuri.org/IAdministradorService/CrearNuevoAdministradorResponse")]
        int CrearNuevoAdministrador(IndignaFwk.Common.Entities.Administrador administrador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorService/ObtenerListadoAdministradores", ReplyAction="http://tempuri.org/IAdministradorService/ObtenerListadoAdministradoresResponse")]
        System.Collections.Generic.List<IndignaFwk.Common.Entities.Administrador> ObtenerListadoAdministradores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorService/ObtenerAdministradorPorId", ReplyAction="http://tempuri.org/IAdministradorService/ObtenerAdministradorPorIdResponse")]
        IndignaFwk.Common.Entities.Administrador ObtenerAdministradorPorId(int idAdministrador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorService/ObtenerAdministradorPorEmailYPass", ReplyAction="http://tempuri.org/IAdministradorService/ObtenerAdministradorPorEmailYPassRespons" +
            "e")]
        IndignaFwk.Common.Entities.Administrador ObtenerAdministradorPorEmailYPass(string email, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorService/EditarAdministrador", ReplyAction="http://tempuri.org/IAdministradorService/EditarAdministradorResponse")]
        void EditarAdministrador(IndignaFwk.Common.Entities.Administrador administrador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorService/EliminarAdministrador", ReplyAction="http://tempuri.org/IAdministradorService/EliminarAdministradorResponse")]
        void EliminarAdministrador(int idAdministrador);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdministradorServiceChannel : IndignaFwk.UI.Process.AdministradorService.IAdministradorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdministradorServiceClient : System.ServiceModel.ClientBase<IndignaFwk.UI.Process.AdministradorService.IAdministradorService>, IndignaFwk.UI.Process.AdministradorService.IAdministradorService {
        
        public AdministradorServiceClient() {
        }
        
        public AdministradorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdministradorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CrearNuevoAdministrador(IndignaFwk.Common.Entities.Administrador administrador) {
            return base.Channel.CrearNuevoAdministrador(administrador);
        }
        
        public System.Collections.Generic.List<IndignaFwk.Common.Entities.Administrador> ObtenerListadoAdministradores() {
            return base.Channel.ObtenerListadoAdministradores();
        }
        
        public IndignaFwk.Common.Entities.Administrador ObtenerAdministradorPorId(int idAdministrador) {
            return base.Channel.ObtenerAdministradorPorId(idAdministrador);
        }
        
        public IndignaFwk.Common.Entities.Administrador ObtenerAdministradorPorEmailYPass(string email, string pass) {
            return base.Channel.ObtenerAdministradorPorEmailYPass(email, pass);
        }
        
        public void EditarAdministrador(IndignaFwk.Common.Entities.Administrador administrador) {
            base.Channel.EditarAdministrador(administrador);
        }
        
        public void EliminarAdministrador(int idAdministrador) {
            base.Channel.EliminarAdministrador(idAdministrador);
        }
    }
}
