//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndignaFwk.UI.Process.GrupoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GrupoService.IGrupoService")]
    public interface IGrupoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrupoService/CrearNuevoGrupo", ReplyAction="http://tempuri.org/IGrupoService/CrearNuevoGrupoResponse")]
        int CrearNuevoGrupo(IndignaFwk.Common.Entities.Grupo grupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrupoService/ObtenerListadoGrupos", ReplyAction="http://tempuri.org/IGrupoService/ObtenerListadoGruposResponse")]
        System.Collections.Generic.List<IndignaFwk.Common.Entities.Grupo> ObtenerListadoGrupos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrupoService/ObtenerGrupoPorId", ReplyAction="http://tempuri.org/IGrupoService/ObtenerGrupoPorIdResponse")]
        IndignaFwk.Common.Entities.Grupo ObtenerGrupoPorId(int idGrupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrupoService/ObtenerGrupoPorUrl", ReplyAction="http://tempuri.org/IGrupoService/ObtenerGrupoPorUrlResponse")]
        IndignaFwk.Common.Entities.Grupo ObtenerGrupoPorUrl(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrupoService/EditarGrupo", ReplyAction="http://tempuri.org/IGrupoService/EditarGrupoResponse")]
        void EditarGrupo(IndignaFwk.Common.Entities.Grupo grupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrupoService/EliminarGrupo", ReplyAction="http://tempuri.org/IGrupoService/EliminarGrupoResponse")]
        void EliminarGrupo(int idGrupo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGrupoServiceChannel : IndignaFwk.UI.Process.GrupoService.IGrupoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GrupoServiceClient : System.ServiceModel.ClientBase<IndignaFwk.UI.Process.GrupoService.IGrupoService>, IndignaFwk.UI.Process.GrupoService.IGrupoService {
        
        public GrupoServiceClient() {
        }
        
        public GrupoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GrupoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GrupoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GrupoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CrearNuevoGrupo(IndignaFwk.Common.Entities.Grupo grupo) {
            return base.Channel.CrearNuevoGrupo(grupo);
        }
        
        public System.Collections.Generic.List<IndignaFwk.Common.Entities.Grupo> ObtenerListadoGrupos() {
            return base.Channel.ObtenerListadoGrupos();
        }
        
        public IndignaFwk.Common.Entities.Grupo ObtenerGrupoPorId(int idGrupo) {
            return base.Channel.ObtenerGrupoPorId(idGrupo);
        }
        
        public IndignaFwk.Common.Entities.Grupo ObtenerGrupoPorUrl(string url) {
            return base.Channel.ObtenerGrupoPorUrl(url);
        }
        
        public void EditarGrupo(IndignaFwk.Common.Entities.Grupo grupo) {
            base.Channel.EditarGrupo(grupo);
        }
        
        public void EliminarGrupo(int idGrupo) {
            base.Channel.EliminarGrupo(idGrupo);
        }
    }
}
