//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndignaFwk.Business.Agents.InG4Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InG4Service.IExposeService")]
    public interface IExposeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExposeService/ObtenerContenidosPorTematica", ReplyAction="http://tempuri.org/IExposeService/ObtenerContenidosPorTematicaResponse")]
        System.Collections.Generic.List<IndignaFwk.Common.Entities.Contenido> ObtenerContenidosPorTematica(int idTematica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExposeService/ObtenerConvocatoriasPorTematica", ReplyAction="http://tempuri.org/IExposeService/ObtenerConvocatoriasPorTematicaResponse")]
        System.Collections.Generic.List<IndignaFwk.Common.Entities.Convocatoria> ObtenerConvocatoriasPorTematica(int idTematica);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExposeServiceChannel : IndignaFwk.Business.Agents.InG4Service.IExposeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExposeServiceClient : System.ServiceModel.ClientBase<IndignaFwk.Business.Agents.InG4Service.IExposeService>, IndignaFwk.Business.Agents.InG4Service.IExposeService {
        
        public ExposeServiceClient() {
        }
        
        public ExposeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExposeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExposeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExposeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<IndignaFwk.Common.Entities.Contenido> ObtenerContenidosPorTematica(int idTematica) {
            return base.Channel.ObtenerContenidosPorTematica(idTematica);
        }
        
        public System.Collections.Generic.List<IndignaFwk.Common.Entities.Convocatoria> ObtenerConvocatoriasPorTematica(int idTematica) {
            return base.Channel.ObtenerConvocatoriasPorTematica(idTematica);
        }
    }
}
